name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때 작동

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. 백엔드 레포지토리 폴더로 쏙 들어가서 최신 코드 당겨오기!
            cd /home/ubuntu/lumos/backend
            git pull origin main
            
            # 2. 도커를 실행하려면 docker-compose.yml이 있는 부모 폴더(인프라 폴더)로 한 칸 나와야 함!
            cd /home/ubuntu/lumos
            
            # 3. 도커 빌드 및 실행 (하이픈 없는 최신 명령어)
            sudo docker compose up -d --build
